/**
 * 커버리지 게이트에서 제외되는 **기존 부채** 파일 목록.
 *
 * 이 목록은 승인이 아니라 부채 기록이다. 여기 있는 파일들은 v0.3 이전부터
 * 85% 아래였고 **담당자가 없다**. SPEC-V03-WORKSPACE-001이 만든 것이 아니며,
 * 이 SPEC이 고칠 의무도 없다 — 다만 그 사실을 조용히 넘기지 않기 위해
 * 한 줄씩 이름을 적어 둔다.
 *
 * **왜 디렉터리 glob이 아니라 파일 단위인가**: `src/hooks/**` 같은 glob으로
 * 제외하면 v0.3이 그 디렉터리에 새로 만드는 파일까지 조용히 게이트를 벗어난다
 * (M5가 src/hooks에 훅을 추가한다). 파일 단위 목록이면 **새 파일은 기본적으로
 * 게이트 안에** 들어오고, 목록은 부채가 갚힐 때마다 줄어들기만 한다.
 *
 * 규칙: 이 목록에 **추가하지 말 것**. 항목을 지우는 방향으로만 움직인다.
 * 새 코드가 85%를 못 맞추면 목록을 늘리는 게 아니라 테스트를 쓴다.
 *
 * 생성 시점: 판 0.2.2 (M3 완료 직후), 98개 파일.
 */
export const LEGACY_COVERAGE_EXCLUSIONS: readonly string[] = [
  'electron/aiClient.ts',
  'electron/aiKeys.ts',
  'electron/assetProtocol.ts',
  'electron/autoUpdater.ts',
  'electron/bibliographyWrite.ts',
  'electron/contextMenu.ts',
  'electron/customCss.ts',
  'electron/fileOps.ts',
  'electron/fs.ts',
  'electron/ipc/ai.ts',
  'electron/ipc/bibliography.ts',
  'electron/ipc/bibliographyFetch.ts',
  'electron/ipc/files.ts',
  'electron/ipc/pandoc.ts',
  'electron/ipc/preferences.ts',
  'electron/ipc/reference.ts',
  'electron/ipc/search.ts',
  'electron/ipc/shell.ts',
  'electron/macros.ts',
  'electron/main.ts',
  'electron/menu.ts',
  'electron/pdfText.ts',
  'electron/preload.ts',
  'electron/referenceDownload.ts',
  'shared/bibtex.ts',
  'shared/ipc-contract.ts',
  'src/App.tsx',
  'src/components/AiCommandPalette.tsx',
  'src/components/AiUsageDashboard.tsx',
  'src/components/CitationSuggestPanel.tsx',
  'src/components/CitePalette.tsx',
  'src/components/EditEntryDialog.tsx',
  'src/components/EditorToolbar.tsx',
  'src/components/ImportReferencesDialog.tsx',
  'src/components/InsertCitationDialog.tsx',
  'src/components/MemoCard.tsx',
  'src/components/OrphanRegisterDialog.tsx',
  'src/components/QuickOpen.tsx',
  'src/components/RenameKeyDialog.tsx',
  'src/components/RightSidebar.tsx',
  'src/components/SettingsDialog.tsx',
  'src/components/Sidebar.tsx',
  'src/components/TableCellActions.tsx',
  'src/components/TableSizePopover.tsx',
  'src/components/TableStylePopover.tsx',
  'src/components/sidebar/FileTree.tsx',
  'src/components/sidebar/FileTreeNode.tsx',
  'src/components/sidebar/MemoTab.tsx',
  'src/components/sidebar/ReferencesTab.tsx',
  'src/components/sidebar/SearchTab.tsx',
  'src/components/sidebar/WorkspaceRoot.tsx',
  'src/components/tableStylePopoverHost.ts',
  'src/editor/MarkdownEditor.tsx',
  'src/editor/atomicInlineMarks.ts',
  'src/editor/atomicMedia.ts',
  'src/editor/decorations/citationHover.ts',
  'src/editor/decorations/index.ts',
  'src/editor/decorations/linkInteract.ts',
  'src/editor/decorations/math.ts',
  'src/editor/decorations/mermaid.ts',
  'src/editor/decorations/table.ts',
  'src/editor/docPath.ts',
  'src/editor/headingHint.ts',
  'src/editor/keymap/emojiAutocomplete.ts',
  'src/editor/keymap/index.ts',
  'src/editor/keymap/macros.ts',
  'src/editor/keymap/setHeading.ts',
  'src/editor/keymap/table.ts',
  'src/editor/keymap/tableNavigation.ts',
  'src/editor/markdownExt/tableStylePlugin.ts',
  'src/editor/openSearch.ts',
  'src/editor/theme.ts',
  'src/editor/viewModes.ts',
  'src/editor/wysiwygEscape.ts',
  'src/export/inlineImages.ts',
  'src/hooks/useActiveHeading.ts',
  'src/hooks/useAiPalette.ts',
  'src/hooks/useAppChromeEffects.ts',
  'src/hooks/useAppCloseGuard.ts',
  'src/hooks/useCitationInsertFlow.ts',
  'src/hooks/useCustomCss.ts',
  'src/hooks/useExportFlow.ts',
  'src/hooks/useFileMenuCommands.ts',
  'src/hooks/useFolderTree.ts',
  'src/hooks/useMemoCaretFocus.ts',
  'src/hooks/useMemoEvents.ts',
  'src/hooks/useMemoSync.ts',
  'src/hooks/useMenuCommandRouter.ts',
  'src/hooks/usePickAndInsertImage.ts',
  'src/hooks/usePreferences.ts',
  'src/hooks/usePreferencesInit.ts',
  'src/hooks/useWorkspaceMenu.ts',
  'src/i18n/t.ts',
  'src/main.tsx',
  'src/store/bibliographyStore.ts',
  'src/store/memoSidecarStore.ts',
  'src/utils/errorSurface.ts',
  'src/utils/relativeTime.ts',
];
